name: flutter_google_places_sdk_macos
description: The macos implementation of Flutter plugin for google places sdk
version: 0.1.4
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_macos
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface:
    git:
      url: https://github.com/nhatphat/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_platform_interface
  flutter_google_places_sdk_http:
    git:
      url: https://github.com/nhatphat/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_http

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  plugin:
    implements: flutter_google_places_sdk
    platforms:
      macos:
        fileName: flutter_google_places_sdk_macos.dart
        dartPluginClass: FlutterGooglePlacesSdkMacosPlugin
